### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by raymondsteen** [opendomainregistry/wefact_module#1]
Updated to 0.2.0 for HostFact rename. Only on domains with ODR I get this error, although everything seems to work OK though.

MySQL-error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_WF.WeFact_Registrar' doesn't exist

**Comment by staticall** [comment]
Hello, @raymondsteen!

Thank you for reporting this bug!

Please, try out latest release, v0.2.1. It should fix this issue.

[v0.2.1.zip](https://github.com/opendomainregistry/wefact_module/files/1954680/v0.2.1.zip)

**Comment by raymondsteen** [comment]
This has fixed the problem, at least no more error messages.
Thanks,
Ray
